# Dependabot configuration for Gradle project

version: 2
updates:
  # Update Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      kotlin-core:
        patterns:
          - "org.jetbrains.kotlin*"
        update-types:
          - "minor"
          - "patch"
      ktor-dependencies:
        patterns:
          - "io.ktor*"
        update-types:
          - "minor"
          - "patch"
      exposed-dependencies:
        patterns:
          - "org.jetbrains.exposed*"
        update-types:
          - "minor"
          - "patch"
      jackson-dependencies:
        patterns:
          - "com.fasterxml.jackson*"
        update-types:
          - "minor"
          - "patch"
      kotlinx-dependencies:
        patterns:
          - "org.jetbrains.kotlinx*"
        update-types:
          - "minor"
          - "patch"
      logging-dependencies:
        patterns:
          - "org.slf4j*"
          - "org.apache.logging.log4j*"
        update-types:
          - "minor"
          - "patch"
      database-dependencies:
        patterns:
          - "org.postgresql*"
          - "com.zaxxer:HikariCP*"
          - "org.flywaydb*"
        update-types:
          - "minor"
          - "patch"
      other-dependencies:
        patterns:
          - "org.redisson*"
          - "com.rabbitmq*"
          - "com.google.dagger*"
        update-types:
          - "minor"
          - "patch"

  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"