{
 "title": "Karya Monitoring Dashboard v1",
 "description": "Dashboard to monitor all the servers/nodes of Karya",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Requests",
   "type": "timeseries",
   "description": "Represents the total number of requests per endpoint made to the Karya Server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ktor_http_server_requests_seconds_count{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "{{address}} {{method}} {{route}} - {{status}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "description": "JVM buffer memory used by the Server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"direct\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Scheduler Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Fetch Open Task Latency",
   "type": "timeseries",
   "description": "Summary of time from when the task was meant to be executed to when it was fetched by the scheduler and pushed to the internal queue. This is useful to accordingly adjust the polling frequency.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "karya_scheduler_task_fetch_latency_seconds_summary",
     "legendFormat": "{{instance}} - p{{quantile}}"
    }
   ]
  },
  {
   "title": "Task Process Latency",
   "type": "timeseries",
   "description": "Summary of time from when the task was fetched from the internal queue to when it was processed by the worker and pushed to the external queue. This is useful to accordingly adjust the number of scheduler workers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "karya_scheduler_task_process_latency_seconds_summary",
     "legendFormat": "{{instance}} - p{{quantile}}"
    }
   ]
  },
  { "title": "Executor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Task Polled Latency",
   "type": "timeseries",
   "description": "Summary of time from when the task was meant to be executed to when it was fetched by the executor. This is useful to accordingly adjust the polling frequency and set the number of executors.",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "karya_executor_task_polled_latency_summary",
     "legendFormat": "{{instance}} - p{{quantile}}"
    }
   ]
  },
  {
   "title": "Task Execution Latency",
   "type": "timeseries",
   "description": "Summary of time from when the executor started executing the task to when it was marked as complete. Note that Karya will only consider a task to be executed \"on-time\" once the execution starts. And not when it has been marked as completed.",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "karya_executor_task_execution_latency_summary",
     "legendFormat": "{{instance}} - p{{quantile}}"
    }
   ]
  },
  {
   "title": "Task Processing rate",
   "type": "timeseries",
   "description": "Rate of tasks being processed by the executor",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(karya_executor_task_success_execution_count_total[5m]) + rate(karya_executor_task_failed_execution_count_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "description": "Successfully executed tasks against total completed tasks",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 27 },
   "targets": [
    { "expression": "($A  * 100) / ($A + $B)", "type": "math" }
   ]
  },
  {
   "title": "Average delta to execution",
   "type": "gauge",
   "description": "This figure represents by what time delta is Karya lagging behind in terms of when it was supposed to execute a task",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "karya_executor_task_execution_latency_summary{quantile=\"0.5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tasks Executed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$failure + $success", "type": "math" }
   ]
  }
 ]
}