scrape_configs:
  - job_name: 'karya-server'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'

  - job_name: 'karya-scheduler'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'karya-executor'
    static_configs:
      - targets: ['host.docker.internal:8082']
