application:
  connectors:

    - type: "restapi"
      configs:
        keepAliveTime: 3000
        connectionTimeout: 1000
        connectionAttempts: 3

    - type: "slackmessage"
      configs:
        token: "xoxb"
