repo:
  provider: "psql"
  partitions: 5
  properties:
    hikari:
      dataSourceClassName: "org.postgresql.ds.PGSimpleDataSource"
      dataSource.user: "karya"
      dataSource.password: "karya"
      dataSource.databaseName: "karya"
      dataSource.portNumber: 5432
      dataSource.serverName: "localhost"
      maximumPoolSize: 1
      connectionTimeout: 5000
    flyway:
      url: "jdbc:postgresql://localhost:5432/karya"
      user: "karya"
      password: "karya"

lock:
  provider: "redis"
  properties:
    url: "redis://localhost:6379"
    waitTime: 1000
    leaseTime: 5000