name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main
      - code_comments

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build documentation
        run: ./gradlew dokkaHtmlMultiModule

      - name: Set up Pages for deployment
        uses: actions/setup-pages@v1
        with:
          build_dir: ./build/dokka/htmlMultiModule  # Path to the generated docs

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/dokka/htmlMultiModule  # Path to the generated docs
