name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
      - dockerize_servers
#    paths:
#      - 'servers/server/**'
#      - 'servers/executor/**'
#      - 'servers/scheduler/**'
#      - 'connectors/**'
#      - 'core/**'
#      - 'data/**'
#      - 'gradle/**'
#      - 'build.gradle.kts'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
      repo_owner_lowercase: ${{ steps.set-repo-owner.outputs.repo_owner_lowercase }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from build.gradle.kts
        id: set-version
        run: |
          VERSION=$(grep -oP 'version\s*=\s*"\K[0-9\.]+' build.gradle.kts)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set repository owner to lowercase
        id: set-repo-owner
        run: |
          REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          echo "repo_owner_lowercase=$REPO_OWNER" >> $GITHUB_OUTPUT

  build_and_push:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - server
          - executor
          - scheduler
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Servers Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./servers/${{ matrix.image }}/deploy/Dockerfile
          push: true
          tags: ghcr.io/${{ needs.setup.outputs.repo_owner_lowercase }}/karya-${{ matrix.image }}:${{ needs.setup.outputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
